// ═══════════════════════════════════════════════
// SHAREMATE PARKING — MOCK DATA
// ═══════════════════════════════════════════════

export const spots = [
  {
    id: 'spot-1',
    name: 'CBD Secure Spot',
    address: 'Collins St, CBD',
    pricing: 'Off-peak',
    price: '$5',
    priceNum: 5,
    pricePer: '3 hrs',
    distance: '3 mins',
    host: {
      name: 'Sarah K.',
      initials: 'SK',
      rating: 4.9,
      bookings: 142,
      since: 2024,
      responseTime: 'under 5 minutes',
    },
    amenities: ['Secure', 'Covered', 'EV Charger'],
    hours: '9 AM – 5 PM',
    date: '29 March 2026',
    time: '9:00 AM – 5:00 PM',
    duration: '3 hours',
    arrivalWindow: 'Arrive within 30 mins of 9 AM',
    bookingId: 'SM-2026-001',
    verifyCode: 'K7Q3',
    basePrice: 5.0,
    guaranteeFee: 0.5,
    totalPrice: '$15.50',
    totalNum: 15.5,
  },
  {
    id: 'spot-2',
    name: 'Apartment Bay 12',
    address: 'Southbank Blvd, Southbank',
    pricing: 'High demand',
    price: '$8',
    priceNum: 8,
    pricePer: '3 hrs',
    distance: '7 mins',
    host: {
      name: 'Mike T.',
      initials: 'MT',
      rating: 4.7,
      bookings: 89,
      since: 2023,
      responseTime: 'under 10 minutes',
    },
    amenities: ['Secure'],
    hours: '8 AM – 6 PM',
    date: '29 March 2026',
    time: '9:00 AM – 5:00 PM',
    duration: '3 hours',
    arrivalWindow: 'Arrive within 30 mins of 9 AM',
    bookingId: 'SM-2026-002',
    verifyCode: 'M4P9',
    basePrice: 8.0,
    guaranteeFee: 0.5,
    totalPrice: '$24.50',
    totalNum: 24.5,
  },
  {
    id: 'spot-3',
    name: 'Flinders Lane Garage',
    address: 'Flinders Lane, CBD',
    pricing: 'Off-peak',
    price: '$7',
    priceNum: 7,
    pricePer: '3 hrs',
    distance: '5 mins',
    host: {
      name: 'Priya N.',
      initials: 'PN',
      rating: 4.8,
      bookings: 67,
      since: 2024,
      responseTime: 'under 5 minutes',
    },
    amenities: ['Covered', 'Secure'],
    hours: '7 AM – 7 PM',
    date: '29 March 2026',
    time: '9:00 AM – 5:00 PM',
    duration: '3 hours',
    arrivalWindow: 'Arrive within 30 mins of 9 AM',
    bookingId: 'SM-2026-003',
    verifyCode: 'F2N8',
    basePrice: 7.0,
    guaranteeFee: 0.5,
    totalPrice: '$21.50',
    totalNum: 21.5,
  },
  {
    id: 'spot-4',
    name: 'Southbank EV Bay',
    address: 'City Rd, Southbank',
    pricing: 'High demand',
    price: '$9',
    priceNum: 9,
    pricePer: '3 hrs',
    distance: '8 mins',
    host: {
      name: 'James R.',
      initials: 'JR',
      rating: 4.9,
      bookings: 54,
      since: 2025,
      responseTime: 'under 5 minutes',
    },
    amenities: ['EV Charger', 'Secure'],
    hours: '6 AM – 10 PM',
    date: '29 March 2026',
    time: '9:00 AM – 5:00 PM',
    duration: '3 hours',
    arrivalWindow: 'Arrive within 30 mins of 9 AM',
    bookingId: 'SM-2026-004',
    verifyCode: 'E9V1',
    basePrice: 9.0,
    guaranteeFee: 0.5,
    totalPrice: '$27.50',
    totalNum: 27.5,
  },
  {
    id: 'spot-5',
    name: 'Russell St Open Lot',
    address: 'Russell St, CBD',
    pricing: 'Off-peak',
    price: '$4',
    priceNum: 4,
    pricePer: '3 hrs',
    distance: '6 mins',
    host: {
      name: 'Emma C.',
      initials: 'EC',
      rating: 4.6,
      bookings: 31,
      since: 2025,
      responseTime: 'under 15 minutes',
    },
    amenities: [],
    hours: '8 AM – 6 PM',
    date: '29 March 2026',
    time: '9:00 AM – 5:00 PM',
    duration: '3 hours',
    arrivalWindow: 'Arrive within 30 mins of 9 AM',
    bookingId: 'SM-2026-005',
    verifyCode: 'R3S7',
    basePrice: 4.0,
    guaranteeFee: 0.5,
    totalPrice: '$12.50',
    totalNum: 12.5,
  },
  {
    id: 'spot-6',
    name: 'Carlton Driveway',
    address: 'Lygon St, Carlton',
    pricing: 'Off-peak',
    price: '$6',
    priceNum: 6,
    pricePer: '3 hrs',
    distance: '9 mins',
    host: {
      name: 'Daniel W.',
      initials: 'DW',
      rating: 4.7,
      bookings: 78,
      since: 2024,
      responseTime: 'under 10 minutes',
    },
    amenities: ['Covered'],
    hours: '7 AM – 8 PM',
    date: '29 March 2026',
    time: '9:00 AM – 5:00 PM',
    duration: '3 hours',
    arrivalWindow: 'Arrive within 30 mins of 9 AM',
    bookingId: 'SM-2026-006',
    verifyCode: 'C6D4',
    basePrice: 6.0,
    guaranteeFee: 0.5,
    totalPrice: '$18.50',
    totalNum: 18.5,
  },
];

export const alternatives = [
  {
    id: 'alt-1',
    name: 'Flinders Lane Bay',
    price: '$6',
    duration: '3 hrs',
    walk: '4 mins walk',
  },
  {
    id: 'alt-2',
    name: 'Russell St Carpark',
    price: '$7',
    duration: '3 hrs',
    walk: '5 mins walk',
  },
  {
    id: 'alt-3',
    name: 'Exhibition St Garage',
    price: '$8',
    duration: '3 hrs',
    walk: '5 mins walk',
  },
];

export const TICKER_START = 47;

export const FILTER_CHIPS = [
  { id: 'covered',  label: 'Covered' },
  { id: 'ev',       label: 'EV Charger' },
  { id: 'secure',   label: 'Secure' },
  { id: 'under10',  label: 'Under $10' },
];
